spring:
  application:
    name: bookfriends
  config:
    import: "classpath:api-key.yml"
  datasource:
    url: jdbc:mysql://localhost:3306/bookfriends
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming: #네이밍 전략을 수동으로 설정
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  mail:
    host: smtp.gmail.com
    port: 587
    username: yhdaneys@gmail.com
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  devtools:
    restart:
      enable: true
    livereload:
      enable: true
  web:
    resources:
      static-locations: file:///C:/BookFriends/uploads/

# 로그
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.boot: DEBUG
    org.springframework: DEBUG
    com.daney.bookfriends: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG #국중 api 테스트를 위해 추가

# 서버
server:
  servlet:
    context-path: /bookfriends
  port: 8080

#file 업로드 경로
file:
  upload-dir: c:/BookFriends/uploads
